name: task 1
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [16,18]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: install node ${{matrix.node}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node}}
            # - name: install dependencies
            #   run: npm install

            - name: install newman cli
              run: npm install -g newman

            - name: run newman
              run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json
